[Control]
Host = ""
Port = 4306
# 连接的超时时间 单位/毫秒
ReadMsgTimeout=10000
#最大客户端连接数
MaxUserNum = 5
# 一个客户端最大的代理数
UserMaxProxyNum = 10

[Proto]
Proto="http"
Host = ""
Port = 4302
Domain = "example.com"

[Proxy]
Host=""
Port=4303

[DataBase]
[DataBase.Redis]
Address = "127.0.0.1:6379"
Password =""
UserName = ""
MaxIdles = 100
MaxOpens = 1000
IdleTimeout = 10
IsMaxConnWait = false
Db=0

[DataBase.Mysql]
Version="8"
UserName="root"
Password="Root123"
Address="193.112.47.13:3306"
Default="information_schema"
Databases=["ray_seep"]